src/Entity/Cmd.php
<?php

namespace App\Entity;

use Date;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\CmdRepository;

/**
 * @ORM\Entity(repositoryClass=CmdRepository::class)
 */
class Cmd
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Design;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $prd;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $duree;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Qte;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Pu;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $CmSlug;

    /**
     * @ORM\ManyToOne(targetEntity=CmdClient::class, inversedBy="Cmd")
     * @ORM\JoinColumn(nullable=false)
     */
    private $cmdClient;

    /**
     * @ORM\Column(type="date")
     */
    private $DateCmd;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $User;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDesign(): ?string
    {
        return $this->Design;
    }

    public function setDesign(string $Design): self
    {
        $this->Design = mb_strtoupper($Design);

        return $this;
    }

    public function getPrd(): ?string
    {
        return $this->prd;
    }

    public function setPrd(?string $prd): self
    {
        $this->prd = $prd;

        return $this;
    }

    public function getDuree(): ?string
    {
        return $this->duree;
    }

    public function setDuree(?string $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getQte(): ?string
    {
        return $this->Qte;
    }

    public function setQte(string $Qte): self
    {
        $this->Qte = $Qte;

        return $this;
    }

    public function getPu(): ?string
    {
        return $this->Pu;
    }

    public function setPu(string $Pu): self
    {
        $this->Pu = $Pu;

        return $this;
    }

    public function getDtCmd(): ?\DateTimeInterface
    {
        return $this->DtCmd;
    }

    public function setDtCmd(\DateTimeInterface $DtCmd): self
    {
        $this->DtCmd = $DtCmd;

        return $this;
    }

    public function getCmSlug(): ?string
    {
        return $this->CmSlug;
    }

    public function setCmSlug(?string $CmSlug): self
    {
        $this->CmSlug = $CmSlug;

        return $this;
    }

    public function getCmdClient(): ?CmdClient
    {
        return $this->cmdClient;
    }

    public function setCmdClient(?CmdClient $cmdClient): self
    {
        $this->cmdClient = $cmdClient;

        return $this;
    }

    public function getDateCmd(): ?\DateTimeInterface
    {
        return $this->DateCmd;
    }

    public function setDateCmd(\DateTimeInterface $DateCmd): self
    {
        $this->DateCmd = $DateCmd;

        return $this;
    }

    public function getUser(): ?string
    {
        return $this->User;
    }

    public function setUser(string $User): self
    {
        $this->User = $User;

        return $this;
    }
}

src/Entity/Params.php
<?php

namespace App\Entity;

use App\Repository\ParamsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ParamsRepository::class)
 */
class Params
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Std;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Frq;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $PAdres;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Bp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Mail;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Telp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $PNif;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $PStat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $PRib;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Tp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $FStd;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $PSlug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Logos;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStd(): ?string
    {
        return $this->Std;
    }

    public function setStd(string $Std): self
    {
        $this->Std = mb_strtoupper($Std);

        return $this;
    }

    public function getFrq(): ?string
    {
        return $this->Frq;
    }

    public function setFrq(string $Frq): self
    {
        $this->Frq = $Frq;

        return $this;
    }

    public function getPAdres(): ?string
    {
        return $this->PAdres;
    }

    public function setPAdres(string $PAdres): self
    {
        $this->PAdres = mb_strtoupper($PAdres);

        return $this;
    }

    public function getBp(): ?string
    {
        return $this->Bp;
    }

    public function setBp(string $Bp): self
    {
        $this->Bp = $Bp;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->Mail;
    }

    public function setMail(string $Mail): self
    {
        $this->Mail = $Mail;

        return $this;
    }

    public function getTelp(): ?string
    {
        return $this->Telp;
    }

    public function setTelp(string $Telp): self
    {
        $this->Telp = $Telp;

        return $this;
    }

    public function getPNif(): ?string
    {
        return $this->PNif;
    }

    public function setPNif(string $PNif): self
    {
        $this->PNif = $PNif;

        return $this;
    }

    public function getPStat(): ?string
    {
        return $this->PStat;
    }

    public function setPStat(string $PStat): self
    {
        $this->PStat = $PStat;

        return $this;
    }

    public function getPRib(): ?string
    {
        return $this->PRib;
    }

    public function setPRib(string $PRib): self
    {
        $this->PRib = $PRib;

        return $this;
    }

    public function getTp(): ?string
    {
        return $this->Tp;
    }

    public function setTp(string $Tp): self
    {
        $this->Tp = $Tp;

        return $this;
    }

    public function getFStd(): ?string
    {
        return $this->FStd;
    }

    public function setFStd(string $FStd): self
    {
        $this->FStd = $FStd;

        return $this;
    }

    public function getPSlug(): ?string
    {
        return $this->PSlug;
    }

    public function setPSlug(string $PSlug): self
    {
        $this->PSlug = $PSlug;

        return $this;
    }

    public function getLogos(): ?string
    {
        return $this->Logos;
    }

    public function setLogos(string $Logos): self
    {
        $this->Logos = $Logos;

        return $this;
    }
}

src/Entity/Project.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use ORM\HasLifecycleCallbacks;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ProjectRepository;

/**
 * @ORM\Entity(repositoryClass=ProjectRepository::class)
 */
class Project
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Version;

    /**
     * @ORM\Column(type="date")
     */
    private $DateSortie;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $fichiers;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Slug;

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * @return void
     */
    public function initialisationSlug()
    {   
        if(empty ($this->Slug))
        {
            $slugify = new Slugify();
            $this->Slug= $slugify->slugify($this->Title."-".$this->Version);
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getVersion(): ?string
    {
        return $this->Version;
    }

    public function setVersion(?string $Version): self
    {
        $this->Version = $Version;

        return $this;
    }

    public function getDateSortie(): ?\DateTimeInterface
    {
        return $this->DateSortie;
    }

    public function setDateSortie(\DateTimeInterface $DateSortie): self
    {
        $this->DateSortie = $DateSortie;

        return $this;
    }

    public function getFichiers(): ?string
    {
        return $this->fichiers;
    }

    public function setFichiers(string $fichiers): self
    {
        $this->fichiers = $fichiers;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->Slug;
    }

    public function setSlug(string $Slug): self
    {
        $this->Slug = $Slug;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use ORM\Assert\File;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(fields={"Pseudo"}, message= "Vous avez déjà inscrit avec cette nom d'utilisateur. Merci de reéssayer avec une autre !")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=4,max=255,minMessage="Nom d'utilisateur trop court, veuillez entrer une nom valide !",maxMessage="Ce nom dépasse le limite !")
     */
    private $Pseudo;

    /**
     * @ORM\Column(type="string", length=255 )
     * @Assert\Length(min=4,max=20,minMessage="Nom d'utilisateur trop court, veuillez entrer une nom valide !",maxMessage="Le mot dépasse le limite !")     * 
     */
    private $mdp;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * 
     */
    private $picture;

    /**
     * @Assert\EqualTo(propertyPath="mdp",message="Code de confirmation incorrect !")
     */
    public $confirmation;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $USlug;

    /**
     * @ORM\ManyToMany(targetEntity=Role::class, mappedBy="users")
     */
    private $userRoles;

    public function __construct()
    {
        $this->userRoles = new ArrayCollection();
    }

    // public function __construct()
    // {
    //     $this->tClass = new ArrayCollection();
    // }

    
    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * Undocumented function
     *
     * @return integer|null
     */
    public function initializeSlug(){
        if(empty($this->USlug)){
            $slugify= new Slugify();
            $this->USlug = $slugify->Slugify($this->Pseudo);
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->Pseudo;
    }

    public function setPseudo(string $Pseudo): self
    {
        $this->Pseudo =  mb_strtoupper($Pseudo);

        return $this;
    }

    public function getMdp(): ?string
    {
        return $this->mdp;
    }

    public function setMdp(string $mdp): self
    {
        $this->mdp = $mdp;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getUSlug(): ?string
    {
        return $this->USlug;
    }

    public function setUSlug(?string $USlug): self
    {
        $this->USlug = $USlug;

        return $this;
    }

    public function getRoles(){
        $roles = $this->userRoles->map(function($role){
            return $role->getTitle();
        })->toArray();
        return $roles;
    }
    public function getPassword(){
        return $this->mdp;
    }
    public function getSalt(){}
    
    public function getUsername(){
        return $this->Pseudo;
    }
    

    public function eraseCredentials(){}

    /**
     * @return Collection<int, Role>
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->removeElement($userRole)) {
            $userRole->removeUser($this);
        }

        return $this;
    }


}

templates/vue/onedev.html.twig
{% extends 'base.html.twig' %}
{% block title %}
{% endblock %}
{% block body %}
<div class="" id="containerdev">
    <div class="fs-2">
        {% include('complement/cplm.html.twig') %}
    </div>
    <div class="container text-white">
    <p class="fs-1">{{dev.title|upper}} {{dev.version}}</p>
        <div class="mx-auto fluid">
            <img src="/img/dev/{{dev.fichiers}}" class="img-fluid rounded"  id="mydev">
        </div>
        <p class="fs-4">{{dev.description}}</p>
        <p class="float-end"><a href="{{path('zfolio')}}" class="btn btn-primary">{{'Retour'}}</a></p>
    </div>
</div>
{% endblock %}

templates/vue/portfolio.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div class="text-secondary container ">
    {{ include ('complement/devhead.html.twig' )}}
    <div class="container">
        {{ include ('data/dev/devdata.html.twig' )}}
    </div>       
</div>       
{% endblock %}
{% block footer %}
<div class="float-end">
    {% include('complement/footer.html.twig') %}
</div> 
{% endblock %}

templates/vue/viewC.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{% set ap = app.user %}
<div class="container mt-3">
    <p class="my-3 text-center text-white fs-3">Liste des toutes les commande</p>
    <div class="row float-none col-12">
        <div class="jumbotron">
            <div class="container col-12">
                <div class="row mb-2">
                    <div class="float-start">
                        {{form_start(form)}}
                            <div class="float-start col-6">
                                <div class="col-8">
                                    {{form_row(form.NomClient)}}
                                </div>
                            </div>
                            <div class="float-start col-3">
                                <div class="col-7">
                                    {{form_row(form.DateCmd)}}
                                </div>
                            </div>
                            <div class="float-start col-lg-2 col-sm-2">
                                <button type="submit" class="btn btn-outline-secondary" id="search">Rechercher</button>
                            </div>
                        {{form_end(form)}}
                    </div>
                </div>
            </div>
        </div>
    {% if cmd | length > 0 %}
        <div class="float-start col-11">
            <table class="table table-striped table table-hover bg-success tb">
                <thead class="text-white text-uppercase">
                    <tr>
                        <th>Date</th>
                        <th>Désignation</th>
                        <th>Période</th>
                        <th>Durée</th>
                        <th class="text-end">Quantité</th>
                        <th class="text-end">Prix unitaire</th>
                        <th class="text-end">Montant</th>
                    {% for roles in ap.userRoles %}
                            {% if roles|upper != "ROLE_SUPERADMIN" %}
                                <th>enregistreur</th>
                                <th class="text-danger text-uppercase fs-5">Action</th>
                            {% elseif roles|upper == "ROLE_SUPERADMIN" %}
                                <th>enregistreur</th>
                            {% endif %}
                    {% endfor %}
                    </tr>
                </thead>
                {% for c in cmd %}
                <tbody class="bg-white">
                    <tr>
                        <td>{{c.DateCmd|date("d/m/Y")}}</td>
                        <td>{{c.Design}}</td>
                        <td>{{c.prd}}</td>
                        <td>{{c.duree}}</td>
                        <td class="text-end">{{c.qte}}</td>
                        <td class="text-end">{{c.pu|number_format(0, ',', ' ')}}</td>
                        <td class="text-end">{{(c.qte * c.pu)|number_format(0, ',', ' ')}}</td>
                        {% for roles in ap.userRoles %}
                        {% if roles|upper != "ROLE_SUPERADMIN" %}
                            {% for user in user %}
                                {% if c.user == user.id %}
                                    <th class="text-center">{{user.Pseudo|upper}}</th>
                                {% endif %}    
                            {% endfor %}
                        <td class="">
                            {% if c.user == UserConnected.id %}
                                <a href="{{path('editcommande',{'CSlug':c.CmSlug})}}" class="btn btn-sm"><i class="fa-solid fa-pen-to-square"></i></a>
                                <a onclick="return confirm('Etes vous sur d avoir supprimer le client nommé  {{c.Design|upper}} ?')" href="{{path('del_cmd',{'slug':c.id})}}" class="btn btn-sm"><i class="fas fa-trash"></i></a>
                            {% endif %}     
                        {% elseif roles|upper == "ROLE_SUPERADMIN" %}
                            {% for user in user %}
                                {% if c.user == user.id %}
                                    <th class="text-center">{{user.Pseudo|upper}}</th>
                                {% endif %}    
                            {% endfor %}
                        {% endif %}
                        <td>
                    </tr>
                </tbody>
                {% endfor %}
                {% endfor %}
            </table>
        </div>
        <div class="float-end col-1">
        {% for roles in ap.userRoles %}
        {% if roles|upper == "ROLE_USER" %}
            <div class="float-end">
                <a href="{{path('Commande')}}"><i class="fs-6 fa-sharp  fa-solid fa-newspaper"></i></a>
            </div>
        {% endif %}
        {% endfor %}
        {% if nom | length > 0  and datecmd | length >0 %}
            <div class="float-end col-10">
                <div class="float-end">
                    <a href="{{path('pnt_fact',{'slug':OneCmd.CmSlug})}}"><i class="fas fa-print mt-3" id="fact"></i></a>
                </div>
            </div>
        {% endif %}
        </div>
    {% else %}
        <p class="fs-1 text-danger text-center"><em>Aucune commande ajoutée</em></p>
    {% endif %}
    </div>
</div>
{% endblock %}

templates/vue/viewDepense.html.twig
{% set ap = app.user %}
{{form_start(filtre)}}
    <div class="float-start mb-2">
        <div class="float-start ">
            {{form_row(filtre.DateDps)}}
        </div>
        <div class="float-start ">
            {{form_row(filtre.Datefin)}}
        </div>
        <div class="col-2 float-end " visible="false"></div>
            <button type="submit" class="btn btn-outline-secondary" id="search">Filtrer</button>
    </div>
    {% if search.DateDps is not null and search.Datefin is not null %}
    <a href="{{ path('printdepense', {'slug': search.DateDps.format('Y-m-d'), 'slug1': search.Datefin.format('Y-m-d')}) }}" class="btn btn-outline-success mb-2 btn btn-sm float-end">Rapport</a>
{% endif %}
{{form_end(filtre)}}
{% if Depense | length > 0 %} 
    <table class="table table-striped table table-hover bg-success">
        <thead class="text-white text-uppercase">
            <tr>
                <th>date</th>
                <th>Désignation</th>
                <th class="text-end">Quantité</th>
                <th class="text-end">Prix unitaire</th>
                <th class="text-end">Montant</th>
                {% for roles in ap.userRoles %}
                    {% if roles|upper != "ROLE_SUPERADMIN" %}
                        <th>enregistreur</th>
                        <th class=" fs-3 text-center">Action</th>
                    {% elseif roles|upper == "ROLE_SUPERADMIN" %}
                        <th>enregistreur</th>
                    {% endif %}
                {% endfor %}
            </tr>
        </thead>
    {% for Depense in Depense %}
        <tbody class="bg-white">
            <tr>
                <td>{{Depense.DateDps|date("d/m/Y")}}</td>
                <td class="text-center">{{Depense.Designation}}</td>
                <td class="text-end">{{Depense.Qte}}</td>
                <td class="text-end">{{Depense.PrixUnitaire|number_format(0, ',', ' ')}}</td>
                <td class="text-end">{{(Depense.Qte * Depense.PrixUnitaire)|number_format(0, ',', ' ')}}</td>
                {% for roles in ap.userRoles %}
                    {% if roles|upper != "ROLE_SUPERADMIN" %}
                            {% for user in users %}
                                {% if Depense.User == user.id %}
                                    <th class="text-center">{{user.Pseudo|upper}}</th>
                                {% endif %}    
                            {% endfor %}
                        {% if Depense.User == user %}
                            <td class="text-center col-1">
                                <a href="{{path ('editdps',{'slug':Depense.slug})}}" class="float-start btn btn-sm "><i class="fa-solid fa-pen-to-square text-success"></i></a>
                                <a onclick="return confirm('Vous êtes sûr de la supprimer ?');" href="{{path ('deldepense',{'slug':Depense.id})}}" class="float-end btn btn-sm"><i class="fas fa-trash text-danger"></i></a>
                        {% endif %}
                        <td>
                    {% elseif roles|upper == "ROLE_SUPERADMIN" %}
                            {% for user in users %}
                                {% if Depense.User == user.id %}
                                    <th class="text-center">{{user.Pseudo|upper}}</th>
                                {% endif %}    
                            {% endfor %}
                        {% endif %}
                {% endfor %}
            </tr>
        </tbody>
    {% endfor %}
    </table>
{% else %}
    <p class="h1 text-center text-danger text-uppercase mt-5"><em>Aucun enregistrement trouvé</em></p>
{% endif %}

templates/vue/viewP.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{% set ap = app.user %}
<div class="container mt-3">
    <div class="container row float-none">
        {% if parm | length > 0 %}
            <table class="table table-striped table table-hover bg-success">
                <thead class="text-white text-uppercase">
                    <tr>
                        <th>Station</th>
                        <th>Fréquence</th>
                        <th>Localisation</th>
                        <th>B.P</th>
                        <th>E-mail</th>
                        <th>téléphone</th>
                        <th>STAT</th>
                        <th>NIF</th>
                        <th>Compte Bancaire</th>
                        <th>TP</th>
                    {% for roles in ap.userRoles %}
                    {% if roles|upper == "ROLE_SUPERADMIN" %}
                        <th>Logos</th>
                    {% elseif roles|upper != "ROLE_USER" %} 
                        <th>Action</th>
                    {% endif %}    
                    {% endfor %} 
                    </tr>
                </thead>
                {% for p in parm %}
                <tbody class="bg-white">
                    <tr>
                        <td>{{p.std}}</td>
                        <td>{{p.frq}} MhZ</td>
                        <td>{{p.padres}}</td>
                        <td>{{p.bp}}</td>
                        <td>{{p.mail}}</td>
                        <td>{{p.Telp}}</td>
                        <td>{{p.pstat}}</td>
                        <td>{{p.pnif}}</td>
                        <td>{{p.prib}}</td>
                        <td>{{p.tp}}</td>
                    {% for roles in ap.userRoles %}
                    {% if roles|upper == "ROLE_SUPERADMIN" %}
                        <td><a href="{{path('paralogos',{'slug':p.pslug})}}"><img src="/img/paramettre/{{p.logos}}" class="rounded"></a></td>
                    {% elseif roles|upper != "ROLE_USER" %}    
                        <td><a href="{{path('params',{'slug':p.pSlug})}}" class="btn btn-sm"><i class="fa-solid fa-pen-to-square"></i></a><td>
                    {% endif %}    
                    {% endfor %}    
                    </tr>
                </tbody>
                {% endfor %}
            </table>
    {% else %}
        <p class="h1 text-danger text-center"><em>Aucune renseignement enregistré</em></p>
    {% endif %}
    </div>
</div>
{% endblock %}

templates/vue/viewU.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{% set ap = app.user %}
<div class="container mt-3">
    <p class="my-3 text-center text-white fs-3">Liste d'utilisateurs</p>
    <div class="container row align-center">
        {% if user | length > 0 %}
            <table class="table table-striped table table-hover bg-success">
                <thead class="text-white text-uppercase">
                    <tr>
                        <th class="col-6">Nom</th>
                        <th class="col-6">Photo</th>
                    {% for roles in ap.userRoles %}
                    {% if roles|upper == "ROLE_SUPERADMIN" %}
                        <th class="text-danger text-uppercase fs-5">Action</th>
                    {% endif %}
                    {% endfor %}
                    </tr>
                </thead>
                {% for l in user %}
                <tbody class="bg-white">
                    <tr>
                        <td>{{l.pseudo}}</td>
                        <td><img src="/img/user/{{l.picture}}" class="rounded"></td>
                        {% for roles in ap.userRoles %}
                            {% if roles|upper == "ROLE_SUPERADMIN" %}
                            <td>
                            <a href="{{path('edit_user')}}" class="btn btn-sm">
                                <i class="fa-solid fa-user-pen"></i>
                            </a>
                        
                            <a href="{{path('del_user',{'id':l.id})}}" class="btn btn-sm">
                                <i class="fas fa-trash"></i>
                            </a>
                        {% endif %}
                        {% endfor %}
                        <td>
                    </tr>
                </tbody>
                {% endfor %}
            </table>
    {% else %}
        <p class="h1 text-danger text-center"><em>Aucune Utilisateur enregistré</em></p>
    {% endif %}
    </div>
</div>
{% endblock %}