src/Entity/Client.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use ORM\HashLifecycleCallBacks;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ClientRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=ClientRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 * fields={"NomCl"}, 
 * message= "Nom du client existe déjà. Merci de reéssayer avec une autre !"
 * )
 */
class Client
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=2,max=225,minMessage="Le nom client sont trop court, veuillez entrer une nom valide !",maxMessage="Ce nom dépasse le limite !")
     */
    private $NomCl;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Adress;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Tel;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(min=13,max=15,minMessage="Le Numero Statistique sont trop court, veuillez entrer un numéro valide !",maxMessage="Ce nom dépasse le limite !")
     */
    private $Stat;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(min=9,max=10,minMessage="Le Numero d'Identité Fiscal sont trop court, veuillez entrer un numéro valide !",maxMessage="Ce nom dépasse le limite !")
     */
    private $Nif;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Rcs;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $RIB;

    /**
     * @ORM\Column(type="string")
     */
    private $Slug;

    /**
     * @ORM\OneToMany(targetEntity=CmdClient::class, mappedBy="Clients", orphanRemoval=true)
     */
    private $cmd;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $User;

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * @return void
     */
    public function initializeSlug()
    {   
        $slugify = new Slugify();
        $this->Slug= $slugify->Slugify($this ->NomCl.'-'.$this->Adress);
    }

    public function slugify()
    {
        return $this->slugify();
    }
    public function __toString(): string
    {
        return $this->getSlug();
    }

    public function __construct()
    {
        $this->CCmd = new ArrayCollection();
        $this->cmd = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCl(): ?string
    {
        return $this->NomCl;
    }

    public function setNomCl(string $NomCl): self
    {
        $this->NomCl = mb_strtoupper($NomCl);

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->Adress;
    }

    public function setAdress(?string $Adress): self
    {
        $this->Adress = mb_strtoupper($Adress);

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(?string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getStat(): ?string
    {
        return $this->Stat;
    }

    public function setStat(?string $Stat): self
    {
        $this->Stat = $Stat;

        return $this;
    }

    public function getNif(): ?string
    {
        return $this->Nif;
    }

    public function setNif(?string $Nif): self
    {
        $this->Nif = $Nif;

        return $this;
    }

    public function getRcs(): ?string
    {
        return $this->Rcs;
    }

    public function setRcs(?string $Rcs): self
    {
        $this->Rcs = $Rcs;

        return $this;
    }

    public function getRIB(): ?string
    {
        return $this->RIB;
    }

    public function setRIB(?string $RIB): self
    {
        $this->RIB = $RIB;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->Slug;
    }

    public function setSlug(string $Slug): self
    {
        $this->Slug = $Slug;

        return $this;
    }

    /**
     * @return Collection<int, CmdClient>
     */
    public function getCmd(): Collection
    {
        return $this->cmd;
    }

    public function addCmd(CmdClient $cmd): self
    {
        if (!$this->cmd->contains($cmd)) {
            $this->cmd[] = $cmd;
            $cmd->setClients($this);
        }

        return $this;
    }

    public function removeCmd(CmdClient $cmd): self
    {
        if ($this->cmd->removeElement($cmd)) {
            // set the owning side to null (unless already changed)
            if ($cmd->getClients() === $this) {
                $cmd->setClients(null);
            }
        }

        return $this;
    }

    public function getUser(): ?string
    {
        return $this->User;
    }

    public function setUser(string $User): self
    {
        $this->User = $User;

        return $this;
    }
}

src/Entity/Cmd.php
<?php

namespace App\Entity;

use Date;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\CmdRepository;

/**
 * @ORM\Entity(repositoryClass=CmdRepository::class)
 */
class Cmd
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Design;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $prd;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $duree;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Qte;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Pu;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $CmSlug;

    /**
     * @ORM\ManyToOne(targetEntity=CmdClient::class, inversedBy="Cmd")
     * @ORM\JoinColumn(nullable=false)
     */
    private $cmdClient;

    /**
     * @ORM\Column(type="date")
     */
    private $DateCmd;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $User;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDesign(): ?string
    {
        return $this->Design;
    }

    public function setDesign(string $Design): self
    {
        $this->Design = mb_strtoupper($Design);

        return $this;
    }

    public function getPrd(): ?string
    {
        return $this->prd;
    }

    public function setPrd(?string $prd): self
    {
        $this->prd = $prd;

        return $this;
    }

    public function getDuree(): ?string
    {
        return $this->duree;
    }

    public function setDuree(?string $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getQte(): ?string
    {
        return $this->Qte;
    }

    public function setQte(string $Qte): self
    {
        $this->Qte = $Qte;

        return $this;
    }

    public function getPu(): ?string
    {
        return $this->Pu;
    }

    public function setPu(string $Pu): self
    {
        $this->Pu = $Pu;

        return $this;
    }

    public function getDtCmd(): ?\DateTimeInterface
    {
        return $this->DtCmd;
    }

    public function setDtCmd(\DateTimeInterface $DtCmd): self
    {
        $this->DtCmd = $DtCmd;

        return $this;
    }

    public function getCmSlug(): ?string
    {
        return $this->CmSlug;
    }

    public function setCmSlug(?string $CmSlug): self
    {
        $this->CmSlug = $CmSlug;

        return $this;
    }

    public function getCmdClient(): ?CmdClient
    {
        return $this->cmdClient;
    }

    public function setCmdClient(?CmdClient $cmdClient): self
    {
        $this->cmdClient = $cmdClient;

        return $this;
    }

    public function getDateCmd(): ?\DateTimeInterface
    {
        return $this->DateCmd;
    }

    public function setDateCmd(\DateTimeInterface $DateCmd): self
    {
        $this->DateCmd = $DateCmd;

        return $this;
    }

    public function getUser(): ?string
    {
        return $this->User;
    }

    public function setUser(string $User): self
    {
        $this->User = $User;

        return $this;
    }
}

src/Entity/Project.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use ORM\HasLifecycleCallbacks;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ProjectRepository;

/**
 * @ORM\Entity(repositoryClass=ProjectRepository::class)
 */
class Project
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Version;

    /**
     * @ORM\Column(type="date")
     */
    private $DateSortie;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $fichiers;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Slug;

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * @return void
     */
    public function initialisationSlug()
    {   
        if(empty ($this->Slug))
        {
            $slugify = new Slugify();
            $this->Slug= $slugify->slugify($this->Title."-".$this->Version);
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getVersion(): ?string
    {
        return $this->Version;
    }

    public function setVersion(?string $Version): self
    {
        $this->Version = $Version;

        return $this;
    }

    public function getDateSortie(): ?\DateTimeInterface
    {
        return $this->DateSortie;
    }

    public function setDateSortie(\DateTimeInterface $DateSortie): self
    {
        $this->DateSortie = $DateSortie;

        return $this;
    }

    public function getFichiers(): ?string
    {
        return $this->fichiers;
    }

    public function setFichiers(string $fichiers): self
    {
        $this->fichiers = $fichiers;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->Slug;
    }

    public function setSlug(string $Slug): self
    {
        $this->Slug = $Slug;

        return $this;
    }
}

templates/data/dev/devdata.html.twig
    {% for d in dev %}
    <div class="container-fluid float-start col-md-2">
        <div class="jumbotron mt-3">
            <h1 class="display-6 text-uppercase">{{d.title|u.truncate(20,'...')}}</h1>
            <div class="mx-auto fluid">
                <img src="/img/dev/{{d.fichiers}}" class="img-fluid rounded"  id="mydev">
            </div>
                <p class="text-uppercase lead">{{d.title}} {{d.version}}</p>                    
                <p class="float-center">{{d.description}}</p>                    
                <p class="float-start"><a href="{{path('vue_dev',{'mo':d.slug})}}" class="btn btn-outline-primary">{{'En savoir plus'|u.truncate(15,'...')}}</a></p>
        </div>
    </div>
    {% endfor %}
    

templates/data/dev/infodata.html.twig
    {% for d in dev %}
    <div class="container-fluid float-start col-md-2">
        <div class="jumbotron mt-3">
            <h1 class="display-4 text-uppercase">{{d.title|u.truncate(8,'...')}}</h1>
            <div class="mx-auto fluid">
                <img src="/dev/user/{{d.fichiers}}" class="img-fluid rounded"  id="mydev">
            </div>
                <p class="text-uppercase lead">{{d.title}} {{d.version}}</p>                    
                <p class="float-center">{{d.description}}</p>                    
                <p class="float-start"><a href="#" class="btn btn-outline-primary">{{'En savoir plus'|u.truncate(12,'...')}}</a></p>
        </div>
    </div>
    {% endfor %}

templates/data/dev/mensuelle.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" lang="Fr-fr">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>{% block title %}FACTURE{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
        <style>
         body{
            /*border:1px solid red;*/
            margin-top:1px;
            margin-bottom:2px;
        }
        .body{
            margin-top:200%;
            margin-bottom:2px;
        }
        .ud{text-decoration:underline}
        .d-block{display:block}
        .d-iblock{display:inline-block}
        .header,.body,{
            margin-top:0px;
            margin-bottom:0px;
            margin-left:0px;
            margin-right:0px;
            /*border:1px solid green*/
        }
        footer{
            margin-top: -1rem;
  margin-bottom: 1rem;
  font-size: 0.875em;
  color: #6c757d;

        }
        .collapse{
            border:1px solid black
        }
        .mt{margin-top:0%}
        .success{color:green}
        .danger{color:red}
        .ml{margin-left:50%;margin-right:0%}
        .card{margin-left:0%;}
        .col-lg-4{margin-left:2%;margin-right:0%}
        .col-lg-4x{margin-left:70%;margin-right:0%}
        .col-lg-12{margin-left:20%;margin-right:10%}
        .col-lg-12x{margin-left:8%;margin-right:15%}
        .col-4{margin-left:0%;margin-right:65%}
        .col-4x{margin-left:0%;margin-right:100%}
        .col-12{margin-left:0%;margin-right:0%}
        .float-start{float:left}
        .float-end{float:right}
        .float-none{float:none; display:block}
        .text-center{text-align:center}
        .text-left{text-align:left}
        .spacer{margin-left:0%;margin-right:23%}
        b,strong {font-weight: bolder;}
table{border-collapse:collapse}
th,td{border:1px solid black}
        .container{float:left}
        .float-start {
  float: left !important;
}

.float-end {
  float: right !important;
}

.float-none {
  float: none !important;
}
.text-center {
  text-align: center !important;
}
.fs-1 {
  font-size: calc(1.375rem + 1.5vw) !important;
}

.fs-2 {
  font-size: calc(1.325rem + 0.9vw) !important;
}

.fs-3 {
  font-size: calc(1.3rem + 0.6vw) !important;
}

.fs-4 {
  font-size: calc(1.275rem + 0.3vw) !important;
}

.fs-5 {
  font-size: 1.25rem !important;
}

.fs-6 {
  font-size: 1rem !important;
}
.mt-0 {
  margin-top: 0 !important;
}

.mt-1 {
  margin-top: 0.25rem !important;
}

.mt-2 {
  margin-top: 0.5rem !important;
}

.mt-3 {
  margin-top: 1rem !important;
}

.mt-4 {
  margin-top: 1.5rem !important;
}

.mt-5 {
  margin-top: 3rem !important;
}

.mt-auto {
  margin-top: auto !important;
}
.col-auto {
  flex: 0 0 auto;
  width: auto;
}

.col-1 {
  flex: 0 0 auto;
  width: 8.33333333%;
}

.col-2 {
  flex: 0 0 auto;
  width: 16.66666667%;
}

.col-3 {
  flex: 0 0 auto;
  width: 25%;
}

.col-4 {
  flex: 0 0 auto;
  width: 33.33333333%;
}

.col-5 {
  flex: 0 0 auto;
  width: 41.66666667%;
}

.col-6 {
  flex: 0 0 auto;
  width: 50%;
}

.col-7 {
  flex: 0 0 auto;
  width: 58.33333333%;
}

.col-8 {
  flex: 0 0 auto;
  width: 66.66666667%;
}

.col-9 {
  flex: 0 0 auto;
  width: 75%;
}

.col-10 {
  flex: 0 0 auto;
  width: 83.33333333%;
}

.col-11 {
  flex: 0 0 auto;
  width: 91.66666667%;
}

.col-12 {
  flex: 0 0 auto;
  width: 100%;
}
        img{
            width:50px;height:50px
        }
        .up{text-transform: uppercase;} 
        </style>
        {% block javascript %}{% endblock %}
    </head>
    <body>
    {% block body %}
    <div class="float-none ">
        <div>
        {% for p in param %}
            <div class="mb-2">
                <img src="{{p.Logos}}" class="mtb-1"/>
                <p class="mb-0 mt-0">{{p.Std}}</p>
                <p class="mb-0 mt-0">FM {{p.Frq}}MhZ</p>
                <p class="mb-0 mt-0">Adresse {{p.PAdres}}</p>
                <p class="mb-0 mt-0">Boite Postale: {{p.Bp}}</p>
                <p class="mb-0 mt-0">Email {{p.Mail}}</p>
                <p class="mb-0 mt-0">Télephone {{p.Telp}}</p>
                <p class="mb-0 mt-0">NIF N° {{p.PNif}}</p>
                <div class="float-none mb-5">
                    <div class="float-start">
                        <p class="mb-0 mt-0">STAT N° {{p.PStat}}</p>
                        <p class="mb-0 mt-0">Compte Bancaire: {{p.PRib}}</p>
                        <p class="mb-0 mt-0">TP {{p.Tp}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="mt-5">
    <p class="mt-5 col-9 text-center up">recaputilation mensuelle </p>
        <table class="text-center col-12 tb ">
            <thead class="up">
                <tr >
                    <th>Mois</th>
                    <th>Désignation</th>
                    <th>Période</th>
                    <th>Durée</th>
                    <th>Quantité</th>
                    <th>Prix unitaire</th>
                    <th>Montant</th>
                </tr>      
            </thead>
            {% for c in cmd %}
            <tbody class="bg-white">
                <tr class="tb">
                    <td class="col-1 text-left">{{c.Mois}}</td>
                    <td class="text-left">{{c.Design}}</td>
                    <td>{{c.prd}}</td>
                    <td>{{c.duree}}</td>
                    <td class="text-end">{{c.qte|number_format(0, ',', ' ')}}</td>
                    <td class="text-end">{{c.pu|number_format(2, ',', ' ')}}</td>
                    <td class="text-end">{{(c.qte * c.pu)|number_format(2, ',', ' ')}}</td>
                </tr>
            </tbody>
            {% endfor %} 
        </table>
    </div>
   <div class="float-start">
    <div class="d-block ">
            <div class="col-12">
                <strong><p class="up float-end col-1">total VALINY</p></strong>
            </div>
            <div class="col-12">
                <p>Arrêtée la présente facture à la somme de :.....Ariary( Ar)</p>
            </div>
            <div class="col-12">
                <p class="float-end ud">Le Directeur</p>
            </div>
        </div>
    </div>
    {% endblock %}
    </body>
</html>

templates/data/dev/techdata.html.twig
    {% for d in dev %}
    <div class="container-fluid float-start col-md-2">
        <div class="jumbotron mt-3">
            <h1 class="display-4 text-uppercase">{{d.title|u.truncate(8,'...')}}</h1>
            <div class="mx-auto fluid">
                <img src="/img/user/{{app.user.picture}}" class="img-fluid rounded"  id="mydev">
            </div>
                <p class="text-uppercase lead">{{d.title}} {{d.version}}</p>                    
                <p class="float-center">{{d.description}}</p>                    
                <p class="float-start"><a href="{{path('vue_dev',{'slug':c.ProjectSlug})}}" class="btn btn-outline-primary">{{'En savoir plus'|u.truncate(12,'...')}}</a></p>
        </div>
    </div>
    {% endfor %}