src/Entity/Cmd.php
<?php

namespace App\Entity;

use Date;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\CmdRepository;

/**
 * @ORM\Entity(repositoryClass=CmdRepository::class)
 */
class Cmd
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Design;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $prd;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $duree;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Qte;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Pu;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $CmSlug;

    /**
     * @ORM\ManyToOne(targetEntity=CmdClient::class, inversedBy="Cmd")
     * @ORM\JoinColumn(nullable=false)
     */
    private $cmdClient;

    /**
     * @ORM\Column(type="date")
     */
    private $DateCmd;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $User;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDesign(): ?string
    {
        return $this->Design;
    }

    public function setDesign(string $Design): self
    {
        $this->Design = mb_strtoupper($Design);

        return $this;
    }

    public function getPrd(): ?string
    {
        return $this->prd;
    }

    public function setPrd(?string $prd): self
    {
        $this->prd = $prd;

        return $this;
    }

    public function getDuree(): ?string
    {
        return $this->duree;
    }

    public function setDuree(?string $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getQte(): ?string
    {
        return $this->Qte;
    }

    public function setQte(string $Qte): self
    {
        $this->Qte = $Qte;

        return $this;
    }

    public function getPu(): ?string
    {
        return $this->Pu;
    }

    public function setPu(string $Pu): self
    {
        $this->Pu = $Pu;

        return $this;
    }

    public function getDtCmd(): ?\DateTimeInterface
    {
        return $this->DtCmd;
    }

    public function setDtCmd(\DateTimeInterface $DtCmd): self
    {
        $this->DtCmd = $DtCmd;

        return $this;
    }

    public function getCmSlug(): ?string
    {
        return $this->CmSlug;
    }

    public function setCmSlug(?string $CmSlug): self
    {
        $this->CmSlug = $CmSlug;

        return $this;
    }

    public function getCmdClient(): ?CmdClient
    {
        return $this->cmdClient;
    }

    public function setCmdClient(?CmdClient $cmdClient): self
    {
        $this->cmdClient = $cmdClient;

        return $this;
    }

    public function getDateCmd(): ?\DateTimeInterface
    {
        return $this->DateCmd;
    }

    public function setDateCmd(\DateTimeInterface $DateCmd): self
    {
        $this->DateCmd = $DateCmd;

        return $this;
    }

    public function getUser(): ?string
    {
        return $this->User;
    }

    public function setUser(string $User): self
    {
        $this->User = $User;

        return $this;
    }
}

src/Entity/Params.php
<?php

namespace App\Entity;

use App\Repository\ParamsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ParamsRepository::class)
 */
class Params
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Std;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Frq;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $PAdres;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Bp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Mail;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Telp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $PNif;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $PStat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $PRib;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Tp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $FStd;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $PSlug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Logos;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStd(): ?string
    {
        return $this->Std;
    }

    public function setStd(string $Std): self
    {
        $this->Std = mb_strtoupper($Std);

        return $this;
    }

    public function getFrq(): ?string
    {
        return $this->Frq;
    }

    public function setFrq(string $Frq): self
    {
        $this->Frq = $Frq;

        return $this;
    }

    public function getPAdres(): ?string
    {
        return $this->PAdres;
    }

    public function setPAdres(string $PAdres): self
    {
        $this->PAdres = mb_strtoupper($PAdres);

        return $this;
    }

    public function getBp(): ?string
    {
        return $this->Bp;
    }

    public function setBp(string $Bp): self
    {
        $this->Bp = $Bp;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->Mail;
    }

    public function setMail(string $Mail): self
    {
        $this->Mail = $Mail;

        return $this;
    }

    public function getTelp(): ?string
    {
        return $this->Telp;
    }

    public function setTelp(string $Telp): self
    {
        $this->Telp = $Telp;

        return $this;
    }

    public function getPNif(): ?string
    {
        return $this->PNif;
    }

    public function setPNif(string $PNif): self
    {
        $this->PNif = $PNif;

        return $this;
    }

    public function getPStat(): ?string
    {
        return $this->PStat;
    }

    public function setPStat(string $PStat): self
    {
        $this->PStat = $PStat;

        return $this;
    }

    public function getPRib(): ?string
    {
        return $this->PRib;
    }

    public function setPRib(string $PRib): self
    {
        $this->PRib = $PRib;

        return $this;
    }

    public function getTp(): ?string
    {
        return $this->Tp;
    }

    public function setTp(string $Tp): self
    {
        $this->Tp = $Tp;

        return $this;
    }

    public function getFStd(): ?string
    {
        return $this->FStd;
    }

    public function setFStd(string $FStd): self
    {
        $this->FStd = $FStd;

        return $this;
    }

    public function getPSlug(): ?string
    {
        return $this->PSlug;
    }

    public function setPSlug(string $PSlug): self
    {
        $this->PSlug = $PSlug;

        return $this;
    }

    public function getLogos(): ?string
    {
        return $this->Logos;
    }

    public function setLogos(string $Logos): self
    {
        $this->Logos = $Logos;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use ORM\Assert\File;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(fields={"Pseudo"}, message= "Vous avez déjà inscrit avec cette nom d'utilisateur. Merci de reéssayer avec une autre !")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=4,max=255,minMessage="Nom d'utilisateur trop court, veuillez entrer une nom valide !",maxMessage="Ce nom dépasse le limite !")
     */
    private $Pseudo;

    /**
     * @ORM\Column(type="string", length=255 )
     * @Assert\Length(min=4,max=20,minMessage="Nom d'utilisateur trop court, veuillez entrer une nom valide !",maxMessage="Le mot dépasse le limite !")     * 
     */
    private $mdp;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * 
     */
    private $picture;

    /**
     * @Assert\EqualTo(propertyPath="mdp",message="Code de confirmation incorrect !")
     */
    public $confirmation;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $USlug;

    /**
     * @ORM\ManyToMany(targetEntity=Role::class, mappedBy="users")
     */
    private $userRoles;

    public function __construct()
    {
        $this->userRoles = new ArrayCollection();
    }

    // public function __construct()
    // {
    //     $this->tClass = new ArrayCollection();
    // }

    
    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * Undocumented function
     *
     * @return integer|null
     */
    public function initializeSlug(){
        if(empty($this->USlug)){
            $slugify= new Slugify();
            $this->USlug = $slugify->Slugify($this->Pseudo);
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->Pseudo;
    }

    public function setPseudo(string $Pseudo): self
    {
        $this->Pseudo =  mb_strtoupper($Pseudo);

        return $this;
    }

    public function getMdp(): ?string
    {
        return $this->mdp;
    }

    public function setMdp(string $mdp): self
    {
        $this->mdp = $mdp;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getUSlug(): ?string
    {
        return $this->USlug;
    }

    public function setUSlug(?string $USlug): self
    {
        $this->USlug = $USlug;

        return $this;
    }

    public function getRoles(){
        $roles = $this->userRoles->map(function($role){
            return $role->getTitle();
        })->toArray();
        return $roles;
    }
    public function getPassword(){
        return $this->mdp;
    }
    public function getSalt(){}
    
    public function getUsername(){
        return $this->Pseudo;
    }
    

    public function eraseCredentials(){}

    /**
     * @return Collection<int, Role>
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->removeElement($userRole)) {
            $userRole->removeUser($this);
        }

        return $this;
    }


}

templates/new/Adcl.html.twig
{% extends 'base.html.twig' %}
{% block head %}{% endblock  %}
{% block body %}
{% form_theme form _self  %}
<div class="container spacer card col-md-4 col-md-offset-3 mt-4">
    <div class="row">
        <div class="panel-primary bg-info fs-2 text-center">Client</div>
        <div class="panel-body">
            <div class="form-group mt-3">
                {{ include ('data/data.html.twig', {form: form,button:('Enregistrer')} )}}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/new/Adclass.html.twig
{% extends 'base.html.twig' %}
{% block head %}{% endblock  %}
{% block body %}
{% form_theme form _self  %}
<div class="container spacer card col-md-4 col-md-offset-3 mt-4">
    <div class="row">
        <div class="panel-primary bg-info fs-2 text-center">Catégorie</div>
        <div class="panel-body">
            <div class="form-group mt-3">
                {{ include ('data/data.html.twig', {form: form,button:('Enregistrer')} )}}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/new/Adcm.html.twig
{% extends 'base.html.twig' %}
{% block head %}{% endblock  %}
{% block body %}
{% form_theme form _self  %}
<div class="container spacer card col-md-4 col-md-offset-3 mt-4">
    <div class="row">
        <div class="panel-primary bg-info fs-2 text-center">Commande</div>
        <div class="panel-body">
            <div class="form-group mt-3">
            {{ include ('data/data.html.twig', {form: form,button:('Enregistrer')} )}}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/new/Adfolio.html.twig
{% extends 'base.html.twig' %}
{% block head %}{% endblock  %}
{% block body %}
{% form_theme form _self  %}
<div class="container spacer card col-md-4 col-md-offset-3 mt-4">
    <div class="row">
        <div class="panel-primary bg-info"><h2 class="text-center">Projet</h2></div>
        <div class="panel-body">
            <div class="form-group mt-3">
                {{ include ('data/data.html.twig', {form: form,button:('Enregistrer')} )}}
                {# {% block _client_CmdClient_widget %}
                    {{ include ('data/data.html.twig', {form: form,button:('Enregistrer')} )}}
                {% endblock %} #}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/new/editClient.html.twig
{% extends 'base.html.twig' %}
{% block head %}{% endblock  %}
{% block body %}
{% form_theme form _self  %}
<div class="container spacer card col-md-4 col-md-offset-3 mt-4">
    <div class="row">
        <div class="panel-primary bg-secondary fs-2 text-center">Editer</div>
        <div class="panel-body">
            <div class="form-group mt-3">
                <div class="form-group mt-3">
                    {{ include ('data/data.html.twig', {form: form,button:('Valider')} )}}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/new/editcl.html.twig
{% extends 'base.html.twig' %}
{% block head %}{% endblock  %}
{% block body %}
{% form_theme form _self  %}
<div class="container spacer card col-md-4 col-md-offset-3 mt-4">
    <div class="row">
        <div class="panel-primary bg-secondary fs-2 text-center">Editer</div>
        <div class="panel-body">
            <div class="form-group mt-3">
                <div class="form-group mt-3">
                    {{ include ('data/data.html.twig', {form: form,button:('Valider')} )}}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/new/editcmd.html.twig
{% extends 'base.html.twig' %}
{% block head %}{% endblock  %}
{% block body %}
{% form_theme form _self  %}
<div class="container spacer card col-md-4 col-md-offset-3 mt-4">
    <div class="row">
        <div class="panel-primary bg-secondary fs-2 text-center">Editer</div>
        <div class="panel-body">
            <div class="form-group mt-3">
            {{ include ('data/data.html.twig', {form: form,button:('Valider')} )}}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/new/editlogo.html.twig
{% extends 'base.html.twig' %}
{% block head %}{% endblock  %}
{% block body %}
{% form_theme form _self  %}
<div class="container spacer card col-md-4 col-md-offset-3 mt-4">
    <div class="row">
        <div class="panel-primary bg-secondary fs-2 text-center">Modifier logo {{param.Std|upper}}</div>
        <div class="float-end mt-2" id="editlogos">
            <div class="float-start">
                <div class="form-group">
                    <label class="control-label">Station: {{param.Std|upper}}</label>
                </div>
                <div class="form-group">
                    <label class="control-label">Fréquence: {{param.Frq|number_format(2,"."," ")}}Mhz FM</label>
                </div>
                <div class="form-group">
                    <label class="control-label ">Adress: {{param.padres|upper}}</label>
                </div>
                <div class="form-group">
                    <label class="control-label text-lowercase">Email:{{param.mail}}</label>
                </div>
                <div class="form-group">
                    <label class="control-label">Contact: {{param.Telp}}</label>
                </div>
            </div>
            <div class="float-end form-group">
                <img src="/img/paramettre/{{param.logos}}" class="rounded">
            </div>
        </div>
        <div class="panel-body">
            <div class="form-group mt-3">
            {{ include ('data/data.html.twig', {form: form,button:('Valider')} )}}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/new/editparam.html.twig
{% extends 'base.html.twig' %}
{% block head %}{% endblock  %}
{% block body %}
{% form_theme form _self  %}
<div class="container spacer card col-md-4 col-md-offset-3 mt-4">
    <div class="row">
        <div class="panel-primary bg-secondary fs-2 text-center">Information{{param.Std|upper}}</div>
        <div class="panel-body">
            <div class="form-group mt-3">
            {{ include ('data/data.html.twig', {form: form,button:('Valider')} )}}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/new/editphoto.html.twig
{% extends 'base.html.twig' %}
{% block head %}{% endblock  %}
{% block body %}
{% form_theme form _self  %}
<div class="container spacer card col-md-4 col-md-offset-3 mt-4">
    <div class="row">
        <div class="panel-primary bg-secondary fs-2 text-center">Mon Profil</div>
        <div class="float-end mt-2" id="editlogos">
            <div class="float-start">
                <div class="form-group">
                    <label class="control-label">Nom: {{user.pseudo|upper}}</label>
                </div>
            </div>
            <div class="float-end form-group">
                <img src="/img/user/{{user.picture}}" class="rounded">
            </div>
        </div>
        <div class="panel-body">
            <div class="form-group mt-3">
            {{ include ('data/data.html.twig', {form: form,button:('Valider')} )}}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/new/index.html.twig
{% extends 'base.html.twig' %}
{% block head %}{% endblock  %}
{% block body %}
{% form_theme form _self  %}
<div class="container col-12 mt-5">
    <div class="row card col-3 float-start">
        <div class="panel-primary bg-secondary fs-2 text-center text-uppercase">{{newdepense.Designation}}</div>
        <div class="body col-md-12">
            <div class="form-group mt-3">
                {{ include ('data/data.html.twig', {form: form,button:('Valider')} )}}
            </div>
        </div>
    </div>
    <div class="row float-end col-8">
        <div class="form-group">
            {{ include ('vue/viewDepense.html.twig')}}
        </div>
    </div>
</div>
{% endblock %}

templates/new/print.html.twig
{% extends 'base.html.twig' %}
{% block head %}{% endblock  %}
{% block body %}
<div class="container col-8 bg-white text-dark ">   
  {{form_start(form)}}
    <div class="xcontainer navbar-responsive sticky-top">
      <div class="float-end col-3 mt-1">
        <button type="submit" class="float-start col-6 btn btn-outline-success">Imprimer</button>
        <a href="{{path ('Liste_cmd')}}" class="float-end btn btn-outline-danger text-decoration-none" >Annuler</a>
      </div>
    </div>
  {{form_end(form)}}
    <div class="text-dark mb-5 mt-4 text-dark">
      {% for p in param %}
        <div class="mb-4 ">
          <img src="/img/paramettre/{{p.Logos}}" class="mb-1 mt-2" id="printlogo"/>
          <p class="mt-0 mb-0">{{(p.Std)}}</p>
          <p class="mt-0 mb-0">FM {{p.Frq}}MhZ</p>
          <p class="mt-0 mb-0">Adresse {{p.PAdres}}</p>
          <p class="mt-0 mb-0">Boite Postale: {{p.Bp}}</p>
          <p class="mt-0 mb-0">Email {{p.Mail}}</p>
          <p class="mt-0 mb-0">Télephone {{p.Telp}}</p>
          <p class="mt-0 mb-0">NIF N° {{p.PNif}}</p>
          <div class="float-none col-12">
            <div class="float-start col-8">
                <p class="mt-0 mb-0">STAT N° {{p.PStat}}</p>
                <p class="mt-0 mb-0">Compte Bancaire: {{p.PRib}}</p>
                <p class="mt-0 mb-0">TP {{p.Tp}}</p>
            </div>
            <div class="float-start mt-2">
                {% if clcm.CClient | length > 0   %}
                  <p class="mt-0 mb-0">Doit: {{clients.NomCl|upper}}</p>
                  <p class="mt-0 mb-0">Adresse: {{clients.Adress|upper}}</p>
                  <p class="mt-0 mb-0">B.C: {{clcm.Dos}}</p>
                  <p class="mt-0 mb-0">N° Diffusion: {{clcm.Dif}}</p>
                  <p class="mt-0 mb-0">Client : {{clcm.CClient}}</p>
                {% else %}
                  <p class="mt-0 mb-0">Doit: {{clients.NomCl|upper}}</p>
                  <p class="mt-0 mb-0">Adresse: {{clients.Adress|upper}}</p>
                {% endif %} 
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    <div class="float-none mt-5 text-center">
      {# <p class="mt-3 mb-0  float-start text-center tr">FACTURE N°: </p> #}
      <table class="table table-striped table table-hover bg-success text-center col-12">
        <thead class="up">
          <tr>
            <th>Désignation</th>
            <th>Période</th>
            <th>Durée</th>
            <th>Quantité</th>
            <th>Prix unitaire</th>
            <th>Montant</th>
          </tr>      
        </thead>
        {% for c in cmd %}
          <tbody class="bg-white text-dark">
            <tr>
              <td class="text-left">{{c.design}}</td>
              <td>{{c.prd}}</td>
              <td>{{c.duree}}</td>
              <td class="text-right">{{c.qte|number_format(0, ',', ' ')}}</td>
              <td class="text-right">{{c.pu|number_format(2, ',', ' ')}}</td>
              <td class="text-right" >{{(c.qte * c.pu)|number_format(2, ',', ' ')}}</td>
            </tr>
          </tbody>
        {% endfor %} 
      </table>
    </div>
    <div class="d-iblock col-12 tw bg-white mb-0 text-dark ">
      <div class="d-block ">
        <strong><p class="up float-end mt-0 mb-0">TOTAL {{total|number_format(0," "," ")}}</p></strong>
      </div>
      <div class="d-block text-dark mt-4 mb-5">
        <p class="mt-2 mb-1 text-dark" id="Nb">Arrêté la présente facture à la somme de <strong>{{Nbtotal|upper}} ARIARY ({{total|number_format(0," "," ")}}Ar)</strong></p>
      </div>
    </div>
</div>
{% endblock %}  